### ISSUE TITLE
Python 3.5 dont work!

### ISSUE THREAD

**Issue by johndiego** [mikeboers/Flask-Images#40]
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    from config import app,db,allowed_file
  File "D:\display\config.py", line 5, in <module>
    from flask.ext.images import resized_img_src
  File "C:\Users\JOHN\Envs\display\lib\site-packages\flask\exthook.py", line 96, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "C:\Users\JOHN\Envs\display\lib\site-packages\flask\_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\JOHN\Envs\display\lib\site-packages\flask_images\__init__.py", line 1, in <module>
    from .core import Images, resized_img_src, resized_img_size, resized_img_attrs, resized_img_tag
  File "C:\Users\JOHN\Envs\display\lib\site-packages\flask_images\core.py", line 3, in <module>
    from cStringIO import StringIO
ImportError: No module named 'cStringIO'

**Comment by mikeboers** [comment]
Thanks for your enthusiasm! This is being worked on at #34.
