### ISSUE TITLE
Flask-Images not working on Python 3.5

### ISSUE THREAD

**Issue by kchomski** [mikeboers/Flask-Images#43]
I'm running Python 3.5.2 on Linux Mint 18.2
```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from app import app
  File "/home/kris/projects/soul/app/__init__.py", line 6, in <module>
    from flask_images import Images
  File "/home/kris/.virtualenvs/soul/lib/python3.5/site-packages/flask_images/__init__.py", line 1, in <module>
    from .core import Images, resized_img_src, resized_img_size, resized_img_attrs, resized_img_tag
  File "/home/kris/.virtualenvs/soul/lib/python3.5/site-packages/flask_images/core.py", line 3, in <module>
    from cStringIO import StringIO
ImportError: No module named 'cStringIO'
```
Quote from [SO question](https://stackoverflow.com/questions/28200366/python-3-4-0-email-package-install-importerror-no-module-named-cstringio) related  to the problem:
> The StringIO and cStringIO modules are gone. Instead, import the io module and use io.StringIO or io.BytesIO for text and data respectively.

**Comment by krsnv** [comment]
In issue #34 was suggested solution, but it's not working without github key — getting git clone error.

```
Obtaining Flask_Images from git+https://github.com/wzuo/Flask-Images.git@d3477b6380d1ee74d21425f787fa194354a1ca2d#egg=Flask_Images (from -r /app/requirements.txt (line 4))
  Cloning https://github.com/wzuo/Flask-Images.git (to d3477b6380d1ee74d21425f787fa194354a1ca2d) to /src/flask-images
  Could not find a tag or branch 'd3477b6380d1ee74d21425f787fa194354a1ca2d', assuming commit.
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:mitsuhiko/flask-sphinx-themes.git' into submodule path 'docs/_themes' failed
Command "git submodule update --init --recursive -q" failed with error code 1 in /src/flask-images
```

**Comment by krsnv** [comment]
Using python 3.4 it's also **not working**.

```
app_1    |   File "/app/app.py", line 10, in <module>
app_1    |     from flask_images import Images
app_1    |   File "/usr/local/lib/python3.4/site-packages/flask_images/__init__.py", line 1, in <module>
app_1    |     from .core import Images, resized_img_src, resized_img_size, resized_img_attrs, resized_img_tag
app_1    |   File "/usr/local/lib/python3.4/site-packages/flask_images/core.py", line 3, in <module>
app_1    |     from cStringIO import StringIO
app_1    | ImportError: No module named 'cStringIO'
```

**Comment by emmanuelito** [comment]
So Flask-Image is NOT working on Python 3. 
Someone knows a workaround ?

**Comment by wzuo** [comment]
@krsnv just clone using https, or use my suggested solution in #34

**Comment by mikeboers** [comment]
v3.0.0 is out right now with Python3 support.
